[platformio]
default_envs = run_rs485

[env]
platform = espressif32
framework = arduino
build_type = release
monitor_speed = 115200
test_build_src = true
check_flags =
	--enable=all
#    --enable=warning
#    --enable=style
#    --enable=performance
#    --enable=portability
#    --enable=information
    -I ../include
check_tool = cppcheck
platform_packages =
	tool-cppcheck@1.260.0
build_flags =
	-D MODBUS_ADDRESS=0x00
	-D MODBUS_TARGET_ADDRESS=0x01
	-D SPI_DATA=33
	-D SPI_CLOCK=23
build_unflags =
	-Os
lib_deps =
	../ModbusLib
upload_port = COM7
monitor_port = COM7

[env:run_rs485]
board = m5stack-atom
lib_deps =
	${env.lib_deps}
	m5stack/M5Atom@^0.1.0
	fastled/FastLED@^3.6.0
build_flags =
	${env.build_flags}
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
#	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
	-D TX1=G26
	-D RX1=G32
	-D MOTOR_PARAMETER_RUNNING=1
test_filter = test_rs485
