# MaSiRo Project.
#     Dancing message
#     Date : 2021/10/30
std_msgs/Header                     header
maid_robot_system_interfaces/FramesNo           frames
std_msgs/Int16                                  id
maid_robot_system_interfaces/ClusterLocation    center
maid_robot_system_interfaces/EulerInt16         neck
maid_robot_system_interfaces/ClusterArm         arm_left
maid_robot_system_interfaces/ClusterArm         arm_right
std_msgs/Float32                                knee_height
maid_robot_system_interfaces/EulerInt16         waist
maid_robot_system_interfaces/ClusterLeg         wheel
