# 瞳の見つめる先やエフェクトを通知するメッセージ
std_msgs/Int32          effect      # 瞳のエフェクト    :
std_msgs/Int32          emotions    # 感情              : get_eye_cmd_angle.linear.x  :
std_msgs/Float64        size        # 瞳のサイズ        : get_eye_cmd_angle.linear.y  :
std_msgs/Float64        distance    # 距離              : get_eye_cmd_angle.linear.z  :
std_msgs/Float64        y           # y 座標            : get_eye_cmd_angle.angular.y :
std_msgs/Float64        x           # x 座標            : get_eye_cmd_angle.angular.z :
std_msgs/Int32          management  # 制御
