; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = debug_m5stack_atom

[env]
platform = espressif32
framework = arduino
build_type = release
monitor_speed = 115200
test_build_src = true
check_flags =
	--enable=all
#    --enable=warning
#    --enable=style
#    --enable=performance
#    --enable=portability
#    --enable=information
#    --platform=native
    -I ../include
    -I ./lib
platform_packages =
	tool-cppcheck@1.260.0
lib_deps =
	m5stack/M5Atom@^0.1.0
	fastled/FastLED@^3.6.0
	https://github.com/MaSiRoProjectOSS/CushyWebServer#feature/v0.4.3
	../../../library/MaidRobotSystemLib
	../../../library/ModbusLib
	../../../library/LibZLAC8015D
check_tool = cppcheck
build_flags =
	-D SETTING_WIFI_STA_DEFAULT_ENABLE=true
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D SETTING_FLAG_INVERT=false
	-D CUSHY_WEB_SERVER_OTA=0
	-D MODBUS_ADDRESS=0x00
	-D MODBUS_TARGET_ADDRESS=0x01
	-D ZLAC_DRIVER=ZLAC8015D_MODBUS
	-D ARDUINO_SERIAL_EVENT_TASK_STACK_SIZE=(1024*28)
	-D SETTING_DEFAULT_FAVICON=0
	-D SPI_DATA=33
	-D SPI_CLOCK=23
build_unflags =
	-Os

[env:m5stack_atom_Masiro]
board = m5stack-atom
lib_deps =
	${env.lib_deps}
build_flags =
	${env.build_flags}
	-D CAST_ID=100
	-D CORE_DEBUG_LEVEL=-1
	-D TX1=G26
	-D RX1=G32
	-D BOARD_INPUT_BAUDRATE=115200
test_filter = test_zlac8015d_ctrl

[env:m5stack_atom_Ciro]
board = m5stack-atom
build_flags =
	${env.build_flags}
	-D CAST_ID=101
	-D CORE_DEBUG_LEVEL=-1
	-D SOC_TX0=G26
	-D SOC_RX0=G32
	-D TX2=G23
	-D RX2=G33
	-D TX1=G25
	-D RX1=G21
	-D BOARD_INPUT_BAUDRATE=38400

[env:m5stack_atom_Ciya]
board = m5stack-atom
build_flags =
	${env.build_flags}
	-D CAST_ID=102
	-D CORE_DEBUG_LEVEL=-1
	-D SOC_TX0=G26
	-D SOC_RX0=G32
	-D TX2=G23
	-D RX2=G33
	-D TX1=G25
	-D RX1=G21
	-D BOARD_INPUT_BAUDRATE=38400

[env:debug_m5stack_atom]
board = m5stack-atom
build_flags =
	${env.build_flags}
	-D CAST_ID=100
#	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
	-D DEBUG_ZLAC=1
	-D DEBUG_TRACE=1
	-D TX1=G26
	-D RX1=G32
	-D BOARD_INPUT_BAUDRATE=115200
test_filter = test_zlac8015d_ctrl
