# MaSiRo Project.
#     Date : 2023/10/01
####################################################

int32 ROTATE_CLOCKWISE_12_O_CLOCK = 0
int32 ROTATE_CLOCKWISE_03_O_CLOCK = 1
int32 ROTATE_CLOCKWISE_06_O_CLOCK = 2
int32 ROTATE_CLOCKWISE_09_O_CLOCK = 3

#bool    mirror
#bool    upside_down
#int32   clockwise
#int32   area_offset_x
#int32   area_offset_y
#int32   area_width
#int32   area_height
int32   resize_width
int32   resize_height
---
sensor_msgs/Image image
