; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
#default_envs = PRIMARY_U094_m5stack_atomLite
#default_envs = REPLICA_A131_m5stack_atomLite

[env]
platform_packages =
	tool-cppcheck @ 1.260.0
check_tool = cppcheck
check_flags = --enable=all
monitor_speed = 115200
build_type = release
#build_type = debug
#build_unflags =
#	-Os
build_flags =
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
	-D DEBUG_TRACE=0
	-D CUSTOM_MODBUS_TYPE=MessageFrame::MODBUS_TYPE::MODBUS_TYPE_RTU_EX

[env:PRIMARY_U094_m5stack_atomLite]
# Isolated RS485 Unit / U094
# https://shop.m5stack.com/products/isolated-rs485-unit
platform = espressif32
board = m5stack-atom
framework = arduino
lib_deps =
	m5stack/M5Atom @ ^0.1.0
	fastled/FastLED @ ^3.7.0
	../../library/ModbusLib
build_flags =
	${env.build_flags}
	-D MODBUS_ADDRESS=0x00
	-D TX1=G26
	-D RX1=G32
#	-D ARDUINO_SERIAL_EVENT_TASK_STACK_SIZE=(1024)
upload_port = COM23
monitor_port = COM23

[env:REPLICA_A131_m5stack_atomLite]
# ATOMIC RS485 Base / A131
# https://shop.m5stack.com/products/atomic-rs485-base
platform = espressif32
board = m5stack-atom
framework = arduino
lib_deps =
	m5stack/M5Atom @ ^0.1.0
	fastled/FastLED @ ^3.7.0
	../../library/ModbusLib
build_flags =
	${env.build_flags}
	-D MODBUS_ADDRESS=0x03
	-D TX1=G19
	-D RX1=G22
	-D ARDUINO_SERIAL_EVENT_TASK_STACK_SIZE=(1024*28)
upload_port = COM7
monitor_port = COM7
