
bool                                                human_detected
maid_robot_system_interfaces/RectFloat              detected_area
maid_robot_system_interfaces/PoseLandmarkModel      landmark
maid_robot_system_interfaces/VideoInfo              video_info

float32                                             min_detection
float32                                             min_tracking
float32                                             visibility_th
