# MaSiRo Project.
#     Date : 2023/10/01
####################################################

int32 EMOTION_NORMAL        = 0
int32 EMOTION_CLOSE         = 1
int32 EMOTION_SMILE         = 2
int32 EMOTION_CLOSE_LEFT    = 3
int32 EMOTION_CLOSE_RIGHT   = 4
int32 EMOTION_WINK_LEFT     = 5
int32 EMOTION_WINK_RIGHT    = 6

int32 PUPIL_EFFECT_NORMAL = 0
int32 PUPIL_EFFECT_ORDER  = 1


int32       emotions
int32       pupil_effect
float32     size
float32     distance

float32     left_x
float32     left_y

float32     right_x
float32     right_y
